kind: Service 
apiVersion: v1 
metadata: 
  name: firebase-blog-backend-service
  namespace: firebase-blog
spec:
  selector:
    app: firebase-blog-backend
  ports:
  - protocol: TCP 
    port: 3000
    targetPort: 3000